//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace remake.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDCategory { get; set; }
        public Nullable<int> IDProvider { get; set; }
        [DisplayName("Tên Sản Phẩm")]
        public string ProductName { get; set; }
        [DisplayName("Đơn Giá")]
        public Nullable<double> Price { get; set; }
        [DisplayName("Số Lương")]
        public Nullable<int> Amount { get; set; }
        [DisplayName("Sản Phẩm Được Mua Nhiều")]
        public Nullable<bool> Poppular { get; set; }
        [DisplayName("Đang Giảm Giá")]
        public Nullable<double> Sale { get; set; }
        [DisplayName("Sản Phẩm Mới")]
        public Nullable<bool> New { get; set; }
        [DisplayName("Hình Ảnh")]
        public byte[] Image { get; set; }
        public string UrlImage { get; set; }
        [DisplayName("Mô Tả")]
        public string DESCRIPTION { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
