//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace remake.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int IDPermission { get; set; }
        public int IDTypeUser { get; set; }
        public string Note { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual TypeUser TypeUser { get; set; }
    }
}
