//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace remake.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class UserWeb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserWeb()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int ID { get; set; }
        [DisplayName("Tên Người Dùng")]
        public string Name { get; set; }
        [DisplayName("Tên Tài khoản")]
        public string UserName { get; set; }
        [DisplayName("Mật Khẩu")]
        public string Password { get; set; }
        [DisplayName("Nhập Lại Mật Khẩu")]
        public string ReenterPassword { get; set; }
        [DisplayName("Số Điện Thoại")]
        public Nullable<int> Phone { get; set; }
        [DisplayName("Email")]
        public string Email { get; set; }
        [DisplayName("Địa Chỉ")]
        public string Address { get; set; }
        public string ResetPasswordCode { get; set; }
        public Nullable<int> TypeUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual TypeUser TypeUser1 { get; set; }
    }
}
