//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace remake.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int ID { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> SDT { get; set; }
        public string Ten_khach_hang { get; set; }
        public string Dia_chi { get; set; }
        public Nullable<int> Tong_tien { get; set; }
        public Nullable<System.DateTime> Ngay_xuat { get; set; }
    
        public virtual UserWeb UserWeb { get; set; }
    }
}
